apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: nasi101/netflix:latest
        resources:
            limits:
              memory: 20Mi
            requests:
              
              memory: 20Mi

        ports:
        - containerPort: 80
