name: Publish Docker image
on:
  push:
    branches: ['main']

  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  pull_request:
      types: [opened, synchronize, reopened]

env:
    IMAGE_DOCKER: 'mescorza/trabajofinal:latest'

    
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
          
          args: >
             -Dsonar.organization=mescorza
             -Dsonar.projectKey=mescorza_trabajofinal
             -Dsonar.projectName=trabajofinal
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 


  dependencytest:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: depecheck_test
    steps: 

    - name: Checkout
      uses: actions/checkout@v2
        
    
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      with:
        project: 'trabajofinal' 
        path: '.'
        format: 'HTML'
        
        
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
 
  push_to_registry:
    needs: dependencytest
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mescorza/trabajofinal
      
     # - name: Build and push Docker image
     #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
     #   with:
     #     context: .
     #     push: true
     #     tags: ${{ steps.meta.outputs.tags }}
     #     labels: ${{ steps.meta.outputs.labels }}

      - name: Build Docker
        run: |
          docker build --tag  $IMAGE_DOCKER .

        #agregar analisis de imagen
        
      - name: Run Trivy vulnerability scanner
        id: trivy-pr
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mescorza/trabajofinal:latest'
          format: 'table'
          #exit-code: 1 PARAMETRO PARA QUIEBRE DE PIPELINE 
          
      - name: Push Docker
        run: | 
          docker push $IMAGE_DOCKER

  deploy:
      needs: push_to_registry
      runs-on: self-hosted
    
      steps:

      - name: Pull de la Imagen Docker
        run: |
          docker pull mescorza/trabajofinal:latest

      - name: Despliegue Aplicaion
        run: |
          #docker run -p 8085:8085 --name trabajofinal-deploy -d $IMAGE_DOCKER 
          #docker run -d --name netflix -p 8081:80 netflix:latest
          docker run -d --name trabajofinal -p 8081:80 trabajofinal:latest
          
      - name: Sleep
        run: | 
           sleep 30


     # - name: Build and push Docker image
     #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
     #   with:
     #     context: .
     #     push: true
     #     tags: ${{ steps.meta.outputs.tags }}
     #     labels: ${{ steps.meta.outputs.labels }}  

      #agregar analisis de DAST
      
     
